name: preprocess

on:
  pull_request_target:
        types: [labeled]

jobs:
  preprocess:
    name: Preprocess raw data
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'accepted for preprocessing')

    steps:
    - uses: actions/checkout@v2
      with:
         fetch-depth: 0
         repository: ${{github.event.pull_request.head.repo.full_name}}


    - id: files
      uses: Ana06/get-changed-files@v1.1

    - id: filesfolders
      run: echo "::set-output name=files::$(for f in ${{ steps.files.outputs.all }}; do basename $(dirname $f); done | sort | uniq)"

    - name: preprocess
      id: preprocessing
      run: Rscript scripts/R/runScripts.R ${{ steps.filesfolders.outputs.files }}

    - name: commit preprocessing
      run: |
        git config --global user.email 'actions@github.com'
        git config --global user.name 'Github Actions'
        git add processed_data
        git commit -m "Preprocessing ${{ steps.filesfolders.outputs.files }}"
        git push origin HEAD

    - name: label as successfully preprocessed
      if: ${{ success() }}
      uses: actions/github-script@v3
      with:
        script: |
          github.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['preprocessing successful']
              })

    - name: label failed
      if: ${{ failure() }}
      uses: actions/github-script@v3
      with:
        script: |
          github.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['preprocessing failed']
              })
