name: preprocess

on: [push, pull_request, pull_request_target]

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: preprocess
      run: mkdir -p processed_data/0012; touch processed_data/0012/test.txt

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Preprocessing 0012