name: preprocess

on:
  pull_request_target:

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
         fetch-depth: 0
         repository: ${{github.event.pull_request.head.repo.full_name}}


    - id: files
      uses: jitterbit/get-changed-files@v1

    - id: filesfolders
      run: echo "::set-output name=files::$(for f in ${{ steps.files.outputs.all }}; do basename $(dirname $f); done | sort | uniq)"

    - name: preprocess
      run: for ds in ${{ steps.filesfolders.outputs.files }}; do mkdir -p processed_data/$ds; touch processed_data/$ds/test.txt; done

    - name: commit preprocessing
      run: |
        git config --global user.email 'actions@github.com'
        git config --global user.name 'Github Actions'
        git add processed_data
        git commit -m "Preprocessing ${{ steps.filesfolders.outputs.files }}"
        git push origin HEAD
