name: preprocess

on:
  pull_request_target:

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: preprocess
      run: mkdir -p processed_data/0011; touch processed_data/0011/test.txt

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Preprocessing
        branch: ${{ github.event.pull_request.head.sha }}