name: preprocess

on:
  pull_request_target:
        types: [labeled]

jobs:
  preprocess:
    name: Preprocess raw data
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'accepted for preprocessing')

    steps:
    - uses: actions/checkout@v2
      with:
         fetch-depth: 0
         repository: ${{github.event.pull_request.head.repo.full_name}}


    - id: files
      uses: Ana06/get-changed-files@v1.1

    - id: filesfolders
      run: echo "::set-output name=files::$(for f in ${{ steps.files.outputs.all }}; do basename $(dirname $f); done | sort | uniq)"

    - name: setup R
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: '3.5.3'

    - name: install R packages
      shell: Rscript {0}
      run: |
        install.packages("classyfireR")
        install.packages("grid")
        install.packages("gridExtra")
        install.packages("rcdk")
        install.packages("rinchi")
        install.packages("tidyverse")
        install.packages("treemapify")
        install.packages("viridis")

    - name: standardize compounds
      run: Rscript scripts/R/compounds_standardize.R ${{ steps.filesfolders.outputs.files }}

    - name: compounds classyfire classes
      run: Rscript scripts/R/compounds_classyfire.R ${{ steps.filesfolders.outputs.files }}

    - name: compounds descriptors
      run: Rscript scripts/R/compounds_descriptors.R ${{ steps.filesfolders.outputs.files }}

    - name: metadata standardization
      run: Rscript scripts/R/metadata_standardize.R ${{ steps.filesfolders.outputs.files }}

    - name: compounds overview
      run: Rscript scripts/R/compounds_overview.R

    - name: metadata overview
      run: Rscript scripts/R/metadata_overview.R

    - name: commit preprocessing
      run: |
        git config --global user.email 'actions@github.com'
        git config --global user.name 'Github Actions'
        git add processed_data
        git commit -m "Preprocessing ${{ steps.filesfolders.outputs.files }}"
        git push origin HEAD

    - name: label as successfully preprocessed
      if: ${{ success() }}
      uses: actions/github-script@v3
      with:
        script: |
          github.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['preprocessing successful']
              })

    - name: label failed
      if: ${{ failure() }}
      uses: actions/github-script@v3
      with:
        script: |
          github.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['preprocessing failed']
              })
