name: preprocess

on:
  pull_request_target:

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
         ref: ${{ github.event.pull_request.head.sha }}

    - name: preprocess
      run: mkdir -p processed_data/0014; touch processed_data/0014/test.txt

    - uses: EndBug/add-and-commit@v7
      with:
        add: 'processed_data'
        message: Preprocessing 0014