name: preprocess

on:
  pull_request_target:

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
         fetch-depth: 0
         repository: ${{github.event.pull_request.head.repo.full_name}}

    - name: preprocess
      run: mkdir -p processed_data/0017; touch processed_data/0017/test.txt

    - name: commit preprocessing
      run: |
        git config --global user.email 'actions@github.com'
        git config --global user.name 'Github Actions'
        git add processed_data
        git commit -m 'Preprocessing 0017'
        git push origin HEAD